### ISSUE TITLE
No work 

### ISSUE THREAD

**Issue by Sins1** [Times-0/Avatar#1]
User@PC-SAM c:\xampp\htdocs\cpps\avatar
# python avatar.py
C:\Python27\lib\site-packages\flask_sqlalchemy\__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
 * Serving Flask app "avatar" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "avatar.py", line 86, in <module>
    app.run(host = 'cdn.avatar.clubpenguin.com', port = 80, debug = True)
  File "C:\Python27\lib\site-packages\flask\app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 795, in run_simple
    s.bind(get_sockaddr(hostname, port, address_family))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno 11001] getaddrinfo failed

What i have to do ? (i use 192.168.0.2 for playing with my family)

**Comment by valid22** [comment]
Can you be more specific? What are you running at, localhost/vps?

**Comment by Sins1** [comment]
Hello, i use XAMPP at localhost. So i use  192.168.0.2 to play with my other friends.

**Comment by valid22** [comment]
So I assume you are hosting in your local pc. In that case use host as localhost or '' (empty string), and a different port.
Whatever, but you might want to change domain on swf files to actually make Avatar appear, do that it access Avatar using this host and port

**Comment by Sins1** [comment]
Ok so i change the host on the Avatar.py (app.run(host = '127.0.0.1', port = 80, debug = True)) but where are swf for change the domain ?

**Comment by valid22** [comment]
Where you want this Avatar to appear?

**Comment by Sins1** [comment]
On the /member/dashboard and on my folder cause there is no folder create like "avatar" or other

**Comment by valid22** [comment]
You run avatar on localhost, on required port. You then change the avatar
url in `js/member.js` file. (Like `localhost:port`)

**Comment by valid22** [comment]
You can follow the docs, login and register section for more info -
https://times-0.github.com/

**Comment by valid22** [comment]
Any improvement?

**Comment by Sins1** [comment]
Yes so my folder create a new folder avatr but no "swid" how to ?

**Comment by valid22** [comment]
What?

**Comment by Sins1** [comment]
Where is located avatar.py a folder was created who call "Avatar" and there is my items but not my all items. So where is my foldee SWID ?

**Comment by valid22** [comment]
It won't create folders with swid, why do you worry about that? It's not
how it works.
